# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kave/control/v1/agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kave/control/v1/agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from kave.common.v1 import common_pb2 as kave_dot_common_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bkave/control/v1/agent.proto\x12\x0fkave.control.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bkave/common/v1/common.proto\"\xa5\x03\n\x05\x41gent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\x12\x0e\n\x06\x65nv_id\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x16\n\tpolicy_id\x18\x06 \x01(\tH\x00\x88\x01\x01\x12\x33\n\x0emonthly_budget\x18\x07 \x01(\x0b\x32\x16.kave.common.v1.AmountH\x01\x88\x01\x01\x12,\n\x06status\x18\x08 \x01(\x0e\x32\x1c.kave.control.v1.AgentStatus\x12)\n\x08metadata\x18\t \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x12\n\ncreated_by\x18\n \x01(\t\x12\x12\n\nupdated_by\x18\x0b \x01(\t\x12\x1a\n\rdeleted_at_ms\x18\x0c \x01(\x03H\x02\x88\x01\x01\x12\x15\n\rcreated_at_ms\x18\r \x01(\x03\x12\x15\n\rupdated_at_ms\x18\x0e \x01(\x03\x42\x0c\n\n_policy_idB\x11\n\x0f_monthly_budgetB\x10\n\x0e_deleted_at_ms\"\xb6\x02\n\x0b\x41gentUpdate\x12\x18\n\x0b\x64\x65scription\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tpolicy_id\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x33\n\x0emonthly_budget\x18\x03 \x01(\x0b\x32\x16.kave.common.v1.AmountH\x02\x88\x01\x01\x12\x31\n\x06status\x18\x04 \x01(\x0e\x32\x1c.kave.control.v1.AgentStatusH\x03\x88\x01\x01\x12)\n\x08metadata\x18\x05 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x17\n\nupdated_by\x18\x06 \x01(\tH\x04\x88\x01\x01\x42\x0e\n\x0c_descriptionB\x0c\n\n_policy_idB\x11\n\x0f_monthly_budgetB\t\n\x07_statusB\r\n\x0b_updated_by*_\n\x0b\x41gentStatus\x12\x1c\n\x18\x41GENT_STATUS_UNSPECIFIED\x10\x00\x12\x17\n\x13\x41GENT_STATUS_ACTIVE\x10\x01\x12\x19\n\x15\x41GENT_STATUS_DISABLED\x10\x02\x42;Z9github.com/kave-io/kave/proto/gen/kave/control/v1;controlb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kave.control.v1.agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/kave-io/kave/proto/gen/kave/control/v1;control'
  _globals['_AGENTSTATUS']._serialized_start=844
  _globals['_AGENTSTATUS']._serialized_end=939
  _globals['_AGENT']._serialized_start=108
  _globals['_AGENT']._serialized_end=529
  _globals['_AGENTUPDATE']._serialized_start=532
  _globals['_AGENTUPDATE']._serialized_end=842
# @@protoc_insertion_point(module_scope)
