# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from kave.control.v1 import auth_pb2 as kave_dot_control_dot_v1_dot_auth__pb2
from kave.control.v1 import org_pb2 as kave_dot_control_dot_v1_dot_org__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kave/control/v1/auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """AuthService exposes user authentication, session, and token management.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/kave.control.v1.AuthService/Register',
                request_serializer=kave_dot_control_dot_v1_dot_auth__pb2.RegisterRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_auth__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/kave.control.v1.AuthService/Login',
                request_serializer=kave_dot_control_dot_v1_dot_auth__pb2.LoginRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_auth__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/kave.control.v1.AuthService/Logout',
                request_serializer=kave_dot_control_dot_v1_dot_auth__pb2.LogoutRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Whoami = channel.unary_unary(
                '/kave.control.v1.AuthService/Whoami',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_org__pb2.User.FromString,
                _registered_method=True)
        self.ChangePassword = channel.unary_unary(
                '/kave.control.v1.AuthService/ChangePassword',
                request_serializer=kave_dot_control_dot_v1_dot_auth__pb2.ChangePasswordRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/kave.control.v1.AuthService/ListSessions',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_auth__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.RevokeSession = channel.unary_unary(
                '/kave.control.v1.AuthService/RevokeSession',
                request_serializer=kave_dot_control_dot_v1_dot_auth__pb2.RevokeSessionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CreateAPIToken = channel.unary_unary(
                '/kave.control.v1.AuthService/CreateAPIToken',
                request_serializer=kave_dot_control_dot_v1_dot_auth__pb2.CreateAPITokenRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_auth__pb2.CreateAPITokenResponse.FromString,
                _registered_method=True)
        self.ListAPITokens = channel.unary_unary(
                '/kave.control.v1.AuthService/ListAPITokens',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_auth__pb2.ListAPITokensResponse.FromString,
                _registered_method=True)
        self.RevokeAPIToken = channel.unary_unary(
                '/kave.control.v1.AuthService/RevokeAPIToken',
                request_serializer=kave_dot_control_dot_v1_dot_auth__pb2.RevokeAPITokenRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CreateAgentToken = channel.unary_unary(
                '/kave.control.v1.AuthService/CreateAgentToken',
                request_serializer=kave_dot_control_dot_v1_dot_auth__pb2.CreateAgentTokenRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_auth__pb2.CreateAgentTokenResponse.FromString,
                _registered_method=True)
        self.ListAgentTokens = channel.unary_unary(
                '/kave.control.v1.AuthService/ListAgentTokens',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_auth__pb2.ListAgentTokensResponse.FromString,
                _registered_method=True)
        self.RevokeAgentToken = channel.unary_unary(
                '/kave.control.v1.AuthService/RevokeAgentToken',
                request_serializer=kave_dot_control_dot_v1_dot_auth__pb2.RevokeAgentTokenRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """AuthService exposes user authentication, session, and token management.
    """

    def Register(self, request, context):
        """Authentication
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Whoami(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangePassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Session management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAPIToken(self, request, context):
        """API token management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAPITokens(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeAPIToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAgentToken(self, request, context):
        """Agent token management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgentTokens(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeAgentToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=kave_dot_control_dot_v1_dot_auth__pb2.RegisterRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_auth__pb2.AuthResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=kave_dot_control_dot_v1_dot_auth__pb2.LoginRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_auth__pb2.AuthResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=kave_dot_control_dot_v1_dot_auth__pb2.LogoutRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Whoami': grpc.unary_unary_rpc_method_handler(
                    servicer.Whoami,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_org__pb2.User.SerializeToString,
            ),
            'ChangePassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangePassword,
                    request_deserializer=kave_dot_control_dot_v1_dot_auth__pb2.ChangePasswordRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_auth__pb2.ListSessionsResponse.SerializeToString,
            ),
            'RevokeSession': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeSession,
                    request_deserializer=kave_dot_control_dot_v1_dot_auth__pb2.RevokeSessionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CreateAPIToken': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAPIToken,
                    request_deserializer=kave_dot_control_dot_v1_dot_auth__pb2.CreateAPITokenRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_auth__pb2.CreateAPITokenResponse.SerializeToString,
            ),
            'ListAPITokens': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAPITokens,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_auth__pb2.ListAPITokensResponse.SerializeToString,
            ),
            'RevokeAPIToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeAPIToken,
                    request_deserializer=kave_dot_control_dot_v1_dot_auth__pb2.RevokeAPITokenRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CreateAgentToken': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAgentToken,
                    request_deserializer=kave_dot_control_dot_v1_dot_auth__pb2.CreateAgentTokenRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_auth__pb2.CreateAgentTokenResponse.SerializeToString,
            ),
            'ListAgentTokens': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgentTokens,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_auth__pb2.ListAgentTokensResponse.SerializeToString,
            ),
            'RevokeAgentToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeAgentToken,
                    request_deserializer=kave_dot_control_dot_v1_dot_auth__pb2.RevokeAgentTokenRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kave.control.v1.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kave.control.v1.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """AuthService exposes user authentication, session, and token management.
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.AuthService/Register',
            kave_dot_control_dot_v1_dot_auth__pb2.RegisterRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_auth__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.AuthService/Login',
            kave_dot_control_dot_v1_dot_auth__pb2.LoginRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_auth__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.AuthService/Logout',
            kave_dot_control_dot_v1_dot_auth__pb2.LogoutRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Whoami(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.AuthService/Whoami',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            kave_dot_control_dot_v1_dot_org__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangePassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.AuthService/ChangePassword',
            kave_dot_control_dot_v1_dot_auth__pb2.ChangePasswordRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.AuthService/ListSessions',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            kave_dot_control_dot_v1_dot_auth__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.AuthService/RevokeSession',
            kave_dot_control_dot_v1_dot_auth__pb2.RevokeSessionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAPIToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.AuthService/CreateAPIToken',
            kave_dot_control_dot_v1_dot_auth__pb2.CreateAPITokenRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_auth__pb2.CreateAPITokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAPITokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.AuthService/ListAPITokens',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            kave_dot_control_dot_v1_dot_auth__pb2.ListAPITokensResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeAPIToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.AuthService/RevokeAPIToken',
            kave_dot_control_dot_v1_dot_auth__pb2.RevokeAPITokenRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAgentToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.AuthService/CreateAgentToken',
            kave_dot_control_dot_v1_dot_auth__pb2.CreateAgentTokenRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_auth__pb2.CreateAgentTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgentTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.AuthService/ListAgentTokens',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            kave_dot_control_dot_v1_dot_auth__pb2.ListAgentTokensResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeAgentToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.AuthService/RevokeAgentToken',
            kave_dot_control_dot_v1_dot_auth__pb2.RevokeAgentTokenRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
