# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kave/control/v1/budget.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kave/control/v1/budget.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from kave.common.v1 import common_pb2 as kave_dot_common_dot_v1_dot_common__pb2
from kave.control.v1 import policy_pb2 as kave_dot_control_dot_v1_dot_policy__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ckave/control/v1/budget.proto\x12\x0fkave.control.v1\x1a\x1bkave/common/v1/common.proto\x1a\x1ckave/control/v1/policy.proto\"\xe9\x01\n\x06\x42udget\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x02 \x01(\t\x12(\n\x08hard_cap\x18\x03 \x01(\x0b\x32\x16.kave.common.v1.Amount\x12-\n\x08soft_cap\x18\x04 \x01(\x0b\x32\x16.kave.common.v1.AmountH\x00\x88\x01\x01\x12-\n\x06period\x18\x05 \x01(\x0e\x32\x1d.kave.control.v1.BudgetPeriod\x12\x15\n\rcreated_at_ms\x18\x06 \x01(\x03\x12\x15\n\rupdated_at_ms\x18\x07 \x01(\x03\x42\x0b\n\t_soft_cap\"\xbc\x01\n\x13\x43reateBudgetRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12(\n\x08hard_cap\x18\x02 \x01(\x0b\x32\x16.kave.common.v1.Amount\x12-\n\x08soft_cap\x18\x03 \x01(\x0b\x32\x16.kave.common.v1.AmountH\x00\x88\x01\x01\x12-\n\x06period\x18\x04 \x01(\x0e\x32\x1d.kave.control.v1.BudgetPeriodB\x0b\n\t_soft_cap\"$\n\x10GetBudgetRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"\'\n\x13\x44\x65leteBudgetRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\tB;Z9github.com/kave-io/kave/proto/gen/kave/control/v1;controlb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kave.control.v1.budget_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/kave-io/kave/proto/gen/kave/control/v1;control'
  _globals['_BUDGET']._serialized_start=109
  _globals['_BUDGET']._serialized_end=342
  _globals['_CREATEBUDGETREQUEST']._serialized_start=345
  _globals['_CREATEBUDGETREQUEST']._serialized_end=533
  _globals['_GETBUDGETREQUEST']._serialized_start=535
  _globals['_GETBUDGETREQUEST']._serialized_end=571
  _globals['_DELETEBUDGETREQUEST']._serialized_start=573
  _globals['_DELETEBUDGETREQUEST']._serialized_end=612
# @@protoc_insertion_point(module_scope)
