# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from kave.control.v1 import agent_pb2 as kave_dot_control_dot_v1_dot_agent__pb2
from kave.control.v1 import budget_pb2 as kave_dot_control_dot_v1_dot_budget__pb2
from kave.control.v1 import control_pb2 as kave_dot_control_dot_v1_dot_control__pb2
from kave.control.v1 import credential_pb2 as kave_dot_control_dot_v1_dot_credential__pb2
from kave.control.v1 import environment_pb2 as kave_dot_control_dot_v1_dot_environment__pb2
from kave.control.v1 import org_pb2 as kave_dot_control_dot_v1_dot_org__pb2
from kave.control.v1 import policy_pb2 as kave_dot_control_dot_v1_dot_policy__pb2
from kave.control.v1 import project_pb2 as kave_dot_control_dot_v1_dot_project__pb2
from kave.control.v1 import token_pb2 as kave_dot_control_dot_v1_dot_token__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kave/control/v1/control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlPlaneServiceStub(object):
    """ControlPlaneAPI exposes organization, project, environment, agent, policy, credential, and token operations.
    v1: gRPC only. HTTP transcoding deferred to v1.1+.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateOrganization = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/CreateOrganization',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.CreateOrganizationRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_org__pb2.Organization.FromString,
                _registered_method=True)
        self.GetOrganization = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/GetOrganization',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.GetOrganizationRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_org__pb2.Organization.FromString,
                _registered_method=True)
        self.ListOrganizations = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/ListOrganizations',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.ListOrganizationsRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_control__pb2.ListOrganizationsResponse.FromString,
                _registered_method=True)
        self.CreateProject = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/CreateProject',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.CreateProjectRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_project__pb2.Project.FromString,
                _registered_method=True)
        self.GetProject = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/GetProject',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.GetProjectRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_project__pb2.Project.FromString,
                _registered_method=True)
        self.ListProjects = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/ListProjects',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.ListProjectsRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_control__pb2.ListProjectsResponse.FromString,
                _registered_method=True)
        self.CreateEnvironment = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/CreateEnvironment',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.CreateEnvironmentRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_environment__pb2.Environment.FromString,
                _registered_method=True)
        self.GetEnvironment = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/GetEnvironment',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.GetEnvironmentRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_environment__pb2.Environment.FromString,
                _registered_method=True)
        self.ListEnvironments = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/ListEnvironments',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.ListEnvironmentsRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_control__pb2.ListEnvironmentsResponse.FromString,
                _registered_method=True)
        self.CreateAgent = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/CreateAgent',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.CreateAgentRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_agent__pb2.Agent.FromString,
                _registered_method=True)
        self.GetAgent = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/GetAgent',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.GetAgentRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_agent__pb2.Agent.FromString,
                _registered_method=True)
        self.ListAgents = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/ListAgents',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.ListAgentsRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_control__pb2.ListAgentsResponse.FromString,
                _registered_method=True)
        self.UpdateAgent = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/UpdateAgent',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.UpdateAgentRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_agent__pb2.Agent.FromString,
                _registered_method=True)
        self.DeleteAgent = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/DeleteAgent',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.DeleteAgentRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RestoreAgent = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/RestoreAgent',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.RestoreAgentRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_agent__pb2.Agent.FromString,
                _registered_method=True)
        self.CreatePolicy = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/CreatePolicy',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.CreatePolicyRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_policy__pb2.PolicyRecord.FromString,
                _registered_method=True)
        self.GetPolicy = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/GetPolicy',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.GetPolicyRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_policy__pb2.PolicyRecord.FromString,
                _registered_method=True)
        self.ListPolicies = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/ListPolicies',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.ListPoliciesRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_control__pb2.ListPoliciesResponse.FromString,
                _registered_method=True)
        self.UpdatePolicy = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/UpdatePolicy',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.UpdatePolicyRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_policy__pb2.PolicyRecord.FromString,
                _registered_method=True)
        self.DeletePolicy = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/DeletePolicy',
                request_serializer=kave_dot_control_dot_v1_dot_policy__pb2.DeletePolicyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ExportPolicy = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/ExportPolicy',
                request_serializer=kave_dot_control_dot_v1_dot_policy__pb2.ExportPolicyRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_policy__pb2.PolicyYAML.FromString,
                _registered_method=True)
        self.ValidatePolicy = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/ValidatePolicy',
                request_serializer=kave_dot_control_dot_v1_dot_policy__pb2.ValidatePolicyRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_policy__pb2.ValidatePolicyResponse.FromString,
                _registered_method=True)
        self.CreateToken = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/CreateToken',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.CreateTokenRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_control__pb2.CreateTokenResponse.FromString,
                _registered_method=True)
        self.GetToken = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/GetToken',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.GetTokenRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_token__pb2.AgentToken.FromString,
                _registered_method=True)
        self.ListTokens = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/ListTokens',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.ListTokensRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_control__pb2.ListTokensResponse.FromString,
                _registered_method=True)
        self.RevokeToken = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/RevokeToken',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.RevokeTokenRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CreateCredential = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/CreateCredential',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.CreateCredentialRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_credential__pb2.ConnectorCredential.FromString,
                _registered_method=True)
        self.GetCredential = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/GetCredential',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.GetCredentialRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_credential__pb2.ConnectorCredential.FromString,
                _registered_method=True)
        self.ListCredentials = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/ListCredentials',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.ListCredentialsRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_control__pb2.ListCredentialsResponse.FromString,
                _registered_method=True)
        self.UpdateCredential = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/UpdateCredential',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.UpdateCredentialRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_credential__pb2.ConnectorCredential.FromString,
                _registered_method=True)
        self.RotateCredential = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/RotateCredential',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.RotateCredentialRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_credential__pb2.ConnectorCredential.FromString,
                _registered_method=True)
        self.RevokeCredential = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/RevokeCredential',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.RevokeCredentialRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteCredential = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/DeleteCredential',
                request_serializer=kave_dot_control_dot_v1_dot_control__pb2.DeleteCredentialRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CreateBudget = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/CreateBudget',
                request_serializer=kave_dot_control_dot_v1_dot_budget__pb2.CreateBudgetRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_budget__pb2.Budget.FromString,
                _registered_method=True)
        self.GetBudget = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/GetBudget',
                request_serializer=kave_dot_control_dot_v1_dot_budget__pb2.GetBudgetRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_budget__pb2.Budget.FromString,
                _registered_method=True)
        self.DeleteBudget = channel.unary_unary(
                '/kave.control.v1.ControlPlaneService/DeleteBudget',
                request_serializer=kave_dot_control_dot_v1_dot_budget__pb2.DeleteBudgetRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ControlPlaneServiceServicer(object):
    """ControlPlaneAPI exposes organization, project, environment, agent, policy, credential, and token operations.
    v1: gRPC only. HTTP transcoding deferred to v1.1+.
    """

    def CreateOrganization(self, request, context):
        """Organization operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrganization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOrganizations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProject(self, request, context):
        """Project operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEnvironment(self, request, context):
        """Environment operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnvironment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEnvironments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAgent(self, request, context):
        """Agent operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePolicy(self, request, context):
        """Policy operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPolicies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidatePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateToken(self, request, context):
        """Token operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTokens(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCredential(self, request, context):
        """Credential operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCredentials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RotateCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBudget(self, request, context):
        """Budget operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBudget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBudget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlPlaneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrganization,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.CreateOrganizationRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_org__pb2.Organization.SerializeToString,
            ),
            'GetOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrganization,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.GetOrganizationRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_org__pb2.Organization.SerializeToString,
            ),
            'ListOrganizations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOrganizations,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.ListOrganizationsRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_control__pb2.ListOrganizationsResponse.SerializeToString,
            ),
            'CreateProject': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProject,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.CreateProjectRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_project__pb2.Project.SerializeToString,
            ),
            'GetProject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProject,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.GetProjectRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_project__pb2.Project.SerializeToString,
            ),
            'ListProjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProjects,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.ListProjectsRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_control__pb2.ListProjectsResponse.SerializeToString,
            ),
            'CreateEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEnvironment,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.CreateEnvironmentRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_environment__pb2.Environment.SerializeToString,
            ),
            'GetEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnvironment,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.GetEnvironmentRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_environment__pb2.Environment.SerializeToString,
            ),
            'ListEnvironments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEnvironments,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.ListEnvironmentsRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_control__pb2.ListEnvironmentsResponse.SerializeToString,
            ),
            'CreateAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAgent,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.CreateAgentRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_agent__pb2.Agent.SerializeToString,
            ),
            'GetAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgent,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.GetAgentRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_agent__pb2.Agent.SerializeToString,
            ),
            'ListAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgents,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.ListAgentsRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_control__pb2.ListAgentsResponse.SerializeToString,
            ),
            'UpdateAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAgent,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.UpdateAgentRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_agent__pb2.Agent.SerializeToString,
            ),
            'DeleteAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAgent,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.DeleteAgentRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RestoreAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreAgent,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.RestoreAgentRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_agent__pb2.Agent.SerializeToString,
            ),
            'CreatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePolicy,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.CreatePolicyRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_policy__pb2.PolicyRecord.SerializeToString,
            ),
            'GetPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicy,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.GetPolicyRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_policy__pb2.PolicyRecord.SerializeToString,
            ),
            'ListPolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPolicies,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.ListPoliciesRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_control__pb2.ListPoliciesResponse.SerializeToString,
            ),
            'UpdatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePolicy,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.UpdatePolicyRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_policy__pb2.PolicyRecord.SerializeToString,
            ),
            'DeletePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePolicy,
                    request_deserializer=kave_dot_control_dot_v1_dot_policy__pb2.DeletePolicyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ExportPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportPolicy,
                    request_deserializer=kave_dot_control_dot_v1_dot_policy__pb2.ExportPolicyRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_policy__pb2.PolicyYAML.SerializeToString,
            ),
            'ValidatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidatePolicy,
                    request_deserializer=kave_dot_control_dot_v1_dot_policy__pb2.ValidatePolicyRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_policy__pb2.ValidatePolicyResponse.SerializeToString,
            ),
            'CreateToken': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateToken,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.CreateTokenRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_control__pb2.CreateTokenResponse.SerializeToString,
            ),
            'GetToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GetToken,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.GetTokenRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_token__pb2.AgentToken.SerializeToString,
            ),
            'ListTokens': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTokens,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.ListTokensRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_control__pb2.ListTokensResponse.SerializeToString,
            ),
            'RevokeToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeToken,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.RevokeTokenRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CreateCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCredential,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.CreateCredentialRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_credential__pb2.ConnectorCredential.SerializeToString,
            ),
            'GetCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCredential,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.GetCredentialRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_credential__pb2.ConnectorCredential.SerializeToString,
            ),
            'ListCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCredentials,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.ListCredentialsRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_control__pb2.ListCredentialsResponse.SerializeToString,
            ),
            'UpdateCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCredential,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.UpdateCredentialRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_credential__pb2.ConnectorCredential.SerializeToString,
            ),
            'RotateCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.RotateCredential,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.RotateCredentialRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_credential__pb2.ConnectorCredential.SerializeToString,
            ),
            'RevokeCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeCredential,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.RevokeCredentialRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCredential,
                    request_deserializer=kave_dot_control_dot_v1_dot_control__pb2.DeleteCredentialRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CreateBudget': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBudget,
                    request_deserializer=kave_dot_control_dot_v1_dot_budget__pb2.CreateBudgetRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_budget__pb2.Budget.SerializeToString,
            ),
            'GetBudget': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBudget,
                    request_deserializer=kave_dot_control_dot_v1_dot_budget__pb2.GetBudgetRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_budget__pb2.Budget.SerializeToString,
            ),
            'DeleteBudget': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBudget,
                    request_deserializer=kave_dot_control_dot_v1_dot_budget__pb2.DeleteBudgetRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kave.control.v1.ControlPlaneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kave.control.v1.ControlPlaneService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlPlaneService(object):
    """ControlPlaneAPI exposes organization, project, environment, agent, policy, credential, and token operations.
    v1: gRPC only. HTTP transcoding deferred to v1.1+.
    """

    @staticmethod
    def CreateOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/CreateOrganization',
            kave_dot_control_dot_v1_dot_control__pb2.CreateOrganizationRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_org__pb2.Organization.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/GetOrganization',
            kave_dot_control_dot_v1_dot_control__pb2.GetOrganizationRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_org__pb2.Organization.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOrganizations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/ListOrganizations',
            kave_dot_control_dot_v1_dot_control__pb2.ListOrganizationsRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_control__pb2.ListOrganizationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/CreateProject',
            kave_dot_control_dot_v1_dot_control__pb2.CreateProjectRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_project__pb2.Project.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/GetProject',
            kave_dot_control_dot_v1_dot_control__pb2.GetProjectRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_project__pb2.Project.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/ListProjects',
            kave_dot_control_dot_v1_dot_control__pb2.ListProjectsRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_control__pb2.ListProjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateEnvironment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/CreateEnvironment',
            kave_dot_control_dot_v1_dot_control__pb2.CreateEnvironmentRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_environment__pb2.Environment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEnvironment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/GetEnvironment',
            kave_dot_control_dot_v1_dot_control__pb2.GetEnvironmentRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_environment__pb2.Environment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEnvironments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/ListEnvironments',
            kave_dot_control_dot_v1_dot_control__pb2.ListEnvironmentsRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_control__pb2.ListEnvironmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/CreateAgent',
            kave_dot_control_dot_v1_dot_control__pb2.CreateAgentRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_agent__pb2.Agent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/GetAgent',
            kave_dot_control_dot_v1_dot_control__pb2.GetAgentRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_agent__pb2.Agent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/ListAgents',
            kave_dot_control_dot_v1_dot_control__pb2.ListAgentsRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_control__pb2.ListAgentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/UpdateAgent',
            kave_dot_control_dot_v1_dot_control__pb2.UpdateAgentRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_agent__pb2.Agent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/DeleteAgent',
            kave_dot_control_dot_v1_dot_control__pb2.DeleteAgentRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/RestoreAgent',
            kave_dot_control_dot_v1_dot_control__pb2.RestoreAgentRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_agent__pb2.Agent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/CreatePolicy',
            kave_dot_control_dot_v1_dot_control__pb2.CreatePolicyRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_policy__pb2.PolicyRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/GetPolicy',
            kave_dot_control_dot_v1_dot_control__pb2.GetPolicyRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_policy__pb2.PolicyRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/ListPolicies',
            kave_dot_control_dot_v1_dot_control__pb2.ListPoliciesRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_control__pb2.ListPoliciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/UpdatePolicy',
            kave_dot_control_dot_v1_dot_control__pb2.UpdatePolicyRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_policy__pb2.PolicyRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/DeletePolicy',
            kave_dot_control_dot_v1_dot_policy__pb2.DeletePolicyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/ExportPolicy',
            kave_dot_control_dot_v1_dot_policy__pb2.ExportPolicyRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_policy__pb2.PolicyYAML.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/ValidatePolicy',
            kave_dot_control_dot_v1_dot_policy__pb2.ValidatePolicyRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_policy__pb2.ValidatePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/CreateToken',
            kave_dot_control_dot_v1_dot_control__pb2.CreateTokenRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_control__pb2.CreateTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/GetToken',
            kave_dot_control_dot_v1_dot_control__pb2.GetTokenRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_token__pb2.AgentToken.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/ListTokens',
            kave_dot_control_dot_v1_dot_control__pb2.ListTokensRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_control__pb2.ListTokensResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/RevokeToken',
            kave_dot_control_dot_v1_dot_control__pb2.RevokeTokenRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/CreateCredential',
            kave_dot_control_dot_v1_dot_control__pb2.CreateCredentialRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_credential__pb2.ConnectorCredential.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/GetCredential',
            kave_dot_control_dot_v1_dot_control__pb2.GetCredentialRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_credential__pb2.ConnectorCredential.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/ListCredentials',
            kave_dot_control_dot_v1_dot_control__pb2.ListCredentialsRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_control__pb2.ListCredentialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/UpdateCredential',
            kave_dot_control_dot_v1_dot_control__pb2.UpdateCredentialRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_credential__pb2.ConnectorCredential.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RotateCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/RotateCredential',
            kave_dot_control_dot_v1_dot_control__pb2.RotateCredentialRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_credential__pb2.ConnectorCredential.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/RevokeCredential',
            kave_dot_control_dot_v1_dot_control__pb2.RevokeCredentialRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/DeleteCredential',
            kave_dot_control_dot_v1_dot_control__pb2.DeleteCredentialRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBudget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/CreateBudget',
            kave_dot_control_dot_v1_dot_budget__pb2.CreateBudgetRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_budget__pb2.Budget.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBudget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/GetBudget',
            kave_dot_control_dot_v1_dot_budget__pb2.GetBudgetRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_budget__pb2.Budget.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBudget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.ControlPlaneService/DeleteBudget',
            kave_dot_control_dot_v1_dot_budget__pb2.DeleteBudgetRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
