# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from kave.control.v1 import daemon_pb2 as kave_dot_control_dot_v1_dot_daemon__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kave/control/v1/daemon_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DaemonServiceStub(object):
    """DaemonService exposes daemon lifecycle and configuration operations.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Status = channel.unary_unary(
                '/kave.control.v1.DaemonService/Status',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_daemon__pb2.DaemonStatusResponse.FromString,
                _registered_method=True)
        self.Doctor = channel.unary_unary(
                '/kave.control.v1.DaemonService/Doctor',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_daemon__pb2.DoctorReportResponse.FromString,
                _registered_method=True)
        self.ConfigView = channel.unary_unary(
                '/kave.control.v1.DaemonService/ConfigView',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_daemon__pb2.ConfigViewResponse.FromString,
                _registered_method=True)
        self.ConfigDiff = channel.unary_unary(
                '/kave.control.v1.DaemonService/ConfigDiff',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_daemon__pb2.ConfigDiffResponse.FromString,
                _registered_method=True)
        self.ConfigPaths = channel.unary_unary(
                '/kave.control.v1.DaemonService/ConfigPaths',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_daemon__pb2.ConfigPathsResponse.FromString,
                _registered_method=True)
        self.BuildPlan = channel.unary_unary(
                '/kave.control.v1.DaemonService/BuildPlan',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_daemon__pb2.ApplyPlanResponse.FromString,
                _registered_method=True)
        self.Apply = channel.unary_unary(
                '/kave.control.v1.DaemonService/Apply',
                request_serializer=kave_dot_control_dot_v1_dot_daemon__pb2.ApplyRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_daemon__pb2.ApplyReportResponse.FromString,
                _registered_method=True)
        self.ConfigReload = channel.unary_unary(
                '/kave.control.v1.DaemonService/ConfigReload',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_daemon__pb2.ConfigReloadReportResponse.FromString,
                _registered_method=True)
        self.AdminStore = channel.unary_unary(
                '/kave.control.v1.DaemonService/AdminStore',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_daemon__pb2.AdminStoreReportResponse.FromString,
                _registered_method=True)


class DaemonServiceServicer(object):
    """DaemonService exposes daemon lifecycle and configuration operations.
    """

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Doctor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigView(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigDiff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigPaths(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuildPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Apply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigReload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdminStore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DaemonServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_daemon__pb2.DaemonStatusResponse.SerializeToString,
            ),
            'Doctor': grpc.unary_unary_rpc_method_handler(
                    servicer.Doctor,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_daemon__pb2.DoctorReportResponse.SerializeToString,
            ),
            'ConfigView': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigView,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_daemon__pb2.ConfigViewResponse.SerializeToString,
            ),
            'ConfigDiff': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigDiff,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_daemon__pb2.ConfigDiffResponse.SerializeToString,
            ),
            'ConfigPaths': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigPaths,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_daemon__pb2.ConfigPathsResponse.SerializeToString,
            ),
            'BuildPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildPlan,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_daemon__pb2.ApplyPlanResponse.SerializeToString,
            ),
            'Apply': grpc.unary_unary_rpc_method_handler(
                    servicer.Apply,
                    request_deserializer=kave_dot_control_dot_v1_dot_daemon__pb2.ApplyRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_daemon__pb2.ApplyReportResponse.SerializeToString,
            ),
            'ConfigReload': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigReload,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_daemon__pb2.ConfigReloadReportResponse.SerializeToString,
            ),
            'AdminStore': grpc.unary_unary_rpc_method_handler(
                    servicer.AdminStore,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_daemon__pb2.AdminStoreReportResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kave.control.v1.DaemonService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kave.control.v1.DaemonService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DaemonService(object):
    """DaemonService exposes daemon lifecycle and configuration operations.
    """

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.DaemonService/Status',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            kave_dot_control_dot_v1_dot_daemon__pb2.DaemonStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Doctor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.DaemonService/Doctor',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            kave_dot_control_dot_v1_dot_daemon__pb2.DoctorReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.DaemonService/ConfigView',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            kave_dot_control_dot_v1_dot_daemon__pb2.ConfigViewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigDiff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.DaemonService/ConfigDiff',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            kave_dot_control_dot_v1_dot_daemon__pb2.ConfigDiffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigPaths(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.DaemonService/ConfigPaths',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            kave_dot_control_dot_v1_dot_daemon__pb2.ConfigPathsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuildPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.DaemonService/BuildPlan',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            kave_dot_control_dot_v1_dot_daemon__pb2.ApplyPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Apply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.DaemonService/Apply',
            kave_dot_control_dot_v1_dot_daemon__pb2.ApplyRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_daemon__pb2.ApplyReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigReload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.DaemonService/ConfigReload',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            kave_dot_control_dot_v1_dot_daemon__pb2.ConfigReloadReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdminStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.DaemonService/AdminStore',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            kave_dot_control_dot_v1_dot_daemon__pb2.AdminStoreReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
