# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kave/control/v1/environment.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kave/control/v1/environment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!kave/control/v1/environment.proto\x12\x0fkave.control.v1\"\xd7\x01\n\x0b\x45nvironment\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04slug\x18\x04 \x01(\t\x12.\n\x04type\x18\x05 \x01(\x0e\x32 .kave.control.v1.EnvironmentType\x12.\n\ntrust_mode\x18\x08 \x01(\x0e\x32\x1a.kave.control.v1.TrustMode\x12\x15\n\rcreated_at_ms\x18\x06 \x01(\x03\x12\x15\n\rupdated_at_ms\x18\x07 \x01(\x03*\xa3\x01\n\x0f\x45nvironmentType\x12 \n\x1c\x45NVIRONMENT_TYPE_UNSPECIFIED\x10\x00\x12\x18\n\x14\x45NVIRONMENT_TYPE_DEV\x10\x01\x12\x1c\n\x18\x45NVIRONMENT_TYPE_STAGING\x10\x02\x12\x19\n\x15\x45NVIRONMENT_TYPE_PROD\x10\x03\x12\x1b\n\x17\x45NVIRONMENT_TYPE_CUSTOM\x10\x04*Y\n\tTrustMode\x12\x1a\n\x16TRUST_MODE_UNSPECIFIED\x10\x00\x12\x15\n\x11TRUST_MODE_STRICT\x10\x01\x12\x19\n\x15TRUST_MODE_PERMISSIVE\x10\x02\x42;Z9github.com/kave-io/kave/proto/gen/kave/control/v1;controlb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kave.control.v1.environment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/kave-io/kave/proto/gen/kave/control/v1;control'
  _globals['_ENVIRONMENTTYPE']._serialized_start=273
  _globals['_ENVIRONMENTTYPE']._serialized_end=436
  _globals['_TRUSTMODE']._serialized_start=438
  _globals['_TRUSTMODE']._serialized_end=527
  _globals['_ENVIRONMENT']._serialized_start=55
  _globals['_ENVIRONMENT']._serialized_end=270
# @@protoc_insertion_point(module_scope)
