# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kave/control/v1/org.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kave/control/v1/org.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19kave/control/v1/org.proto\x12\x0fkave.control.v1\"\x8d\x01\n\x0cOrganization\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04slug\x18\x03 \x01(\t\x12\'\n\x04plan\x18\x04 \x01(\x0e\x32\x19.kave.control.v1.PlanTier\x12\x15\n\rcreated_at_ms\x18\x05 \x01(\x03\x12\x15\n\rupdated_at_ms\x18\x06 \x01(\x03\"\xe5\x01\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06org_id\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x15\n\rpassword_hash\x18\x05 \x01(\t\x12+\n\x06status\x18\x06 \x01(\x0e\x32\x1b.kave.control.v1.UserStatus\x12\x1d\n\x10last_login_at_ms\x18\x07 \x01(\x03H\x00\x88\x01\x01\x12\x15\n\rcreated_at_ms\x18\x08 \x01(\x03\x12\x15\n\rupdated_at_ms\x18\t \x01(\x03\x42\x13\n\x11_last_login_at_ms\"\xa7\x01\n\nMembership\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06org_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12-\n\x04role\x18\x04 \x01(\x0e\x32\x1f.kave.control.v1.MembershipRole\x12\x17\n\ninvited_by\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x15\n\rcreated_at_ms\x18\x06 \x01(\x03\x42\r\n\x0b_invited_by*\x9e\x01\n\x0eMembershipRole\x12\x1f\n\x1bMEMBERSHIP_ROLE_UNSPECIFIED\x10\x00\x12\x19\n\x15MEMBERSHIP_ROLE_ADMIN\x10\x01\x12\x17\n\x13MEMBERSHIP_ROLE_DEV\x10\x02\x12\x1a\n\x16MEMBERSHIP_ROLE_VIEWER\x10\x03\x12\x1b\n\x17MEMBERSHIP_ROLE_BILLING\x10\x04*\\\n\nUserStatus\x12\x1b\n\x17USER_STATUS_UNSPECIFIED\x10\x00\x12\x16\n\x12USER_STATUS_ACTIVE\x10\x01\x12\x19\n\x15USER_STATUS_SUSPENDED\x10\x02*g\n\x08PlanTier\x12\x19\n\x15PLAN_TIER_UNSPECIFIED\x10\x00\x12\x12\n\x0ePLAN_TIER_FREE\x10\x01\x12\x12\n\x0ePLAN_TIER_TEAM\x10\x02\x12\x18\n\x14PLAN_TIER_ENTERPRISE\x10\x03\x42;Z9github.com/kave-io/kave/proto/gen/kave/control/v1;controlb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kave.control.v1.org_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/kave-io/kave/proto/gen/kave/control/v1;control'
  _globals['_MEMBERSHIPROLE']._serialized_start=593
  _globals['_MEMBERSHIPROLE']._serialized_end=751
  _globals['_USERSTATUS']._serialized_start=753
  _globals['_USERSTATUS']._serialized_end=845
  _globals['_PLANTIER']._serialized_start=847
  _globals['_PLANTIER']._serialized_end=950
  _globals['_ORGANIZATION']._serialized_start=47
  _globals['_ORGANIZATION']._serialized_end=188
  _globals['_USER']._serialized_start=191
  _globals['_USER']._serialized_end=420
  _globals['_MEMBERSHIP']._serialized_start=423
  _globals['_MEMBERSHIP']._serialized_end=590
# @@protoc_insertion_point(module_scope)
