# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from kave.control.v1 import rbac_pb2 as kave_dot_control_dot_v1_dot_rbac__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kave/control/v1/rbac_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RBACServiceStub(object):
    """RBACService exposes role-based access control operations.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRole = channel.unary_unary(
                '/kave.control.v1.RBACService/CreateRole',
                request_serializer=kave_dot_control_dot_v1_dot_rbac__pb2.CreateRoleRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_rbac__pb2.Role.FromString,
                _registered_method=True)
        self.ListRoles = channel.unary_unary(
                '/kave.control.v1.RBACService/ListRoles',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_rbac__pb2.ListRolesResponse.FromString,
                _registered_method=True)
        self.GetRole = channel.unary_unary(
                '/kave.control.v1.RBACService/GetRole',
                request_serializer=kave_dot_control_dot_v1_dot_rbac__pb2.GetRoleRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_rbac__pb2.Role.FromString,
                _registered_method=True)
        self.DeleteRole = channel.unary_unary(
                '/kave.control.v1.RBACService/DeleteRole',
                request_serializer=kave_dot_control_dot_v1_dot_rbac__pb2.DeleteRoleRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CreateBinding = channel.unary_unary(
                '/kave.control.v1.RBACService/CreateBinding',
                request_serializer=kave_dot_control_dot_v1_dot_rbac__pb2.CreateBindingRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_rbac__pb2.Binding.FromString,
                _registered_method=True)
        self.ListBindings = channel.unary_unary(
                '/kave.control.v1.RBACService/ListBindings',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_rbac__pb2.ListBindingsResponse.FromString,
                _registered_method=True)
        self.DeleteBinding = channel.unary_unary(
                '/kave.control.v1.RBACService/DeleteBinding',
                request_serializer=kave_dot_control_dot_v1_dot_rbac__pb2.DeleteBindingRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.TestPermission = channel.unary_unary(
                '/kave.control.v1.RBACService/TestPermission',
                request_serializer=kave_dot_control_dot_v1_dot_rbac__pb2.TestPermissionRequest.SerializeToString,
                response_deserializer=kave_dot_control_dot_v1_dot_rbac__pb2.TestPermissionResponse.FromString,
                _registered_method=True)


class RBACServiceServicer(object):
    """RBACService exposes role-based access control operations.
    """

    def CreateRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRoles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBinding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBindings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBinding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestPermission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RBACServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRole': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRole,
                    request_deserializer=kave_dot_control_dot_v1_dot_rbac__pb2.CreateRoleRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_rbac__pb2.Role.SerializeToString,
            ),
            'ListRoles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRoles,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_rbac__pb2.ListRolesResponse.SerializeToString,
            ),
            'GetRole': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRole,
                    request_deserializer=kave_dot_control_dot_v1_dot_rbac__pb2.GetRoleRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_rbac__pb2.Role.SerializeToString,
            ),
            'DeleteRole': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRole,
                    request_deserializer=kave_dot_control_dot_v1_dot_rbac__pb2.DeleteRoleRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CreateBinding': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBinding,
                    request_deserializer=kave_dot_control_dot_v1_dot_rbac__pb2.CreateBindingRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_rbac__pb2.Binding.SerializeToString,
            ),
            'ListBindings': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBindings,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_rbac__pb2.ListBindingsResponse.SerializeToString,
            ),
            'DeleteBinding': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBinding,
                    request_deserializer=kave_dot_control_dot_v1_dot_rbac__pb2.DeleteBindingRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'TestPermission': grpc.unary_unary_rpc_method_handler(
                    servicer.TestPermission,
                    request_deserializer=kave_dot_control_dot_v1_dot_rbac__pb2.TestPermissionRequest.FromString,
                    response_serializer=kave_dot_control_dot_v1_dot_rbac__pb2.TestPermissionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kave.control.v1.RBACService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kave.control.v1.RBACService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RBACService(object):
    """RBACService exposes role-based access control operations.
    """

    @staticmethod
    def CreateRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.RBACService/CreateRole',
            kave_dot_control_dot_v1_dot_rbac__pb2.CreateRoleRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_rbac__pb2.Role.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRoles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.RBACService/ListRoles',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            kave_dot_control_dot_v1_dot_rbac__pb2.ListRolesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.RBACService/GetRole',
            kave_dot_control_dot_v1_dot_rbac__pb2.GetRoleRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_rbac__pb2.Role.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.RBACService/DeleteRole',
            kave_dot_control_dot_v1_dot_rbac__pb2.DeleteRoleRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBinding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.RBACService/CreateBinding',
            kave_dot_control_dot_v1_dot_rbac__pb2.CreateBindingRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_rbac__pb2.Binding.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBindings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.RBACService/ListBindings',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            kave_dot_control_dot_v1_dot_rbac__pb2.ListBindingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBinding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.RBACService/DeleteBinding',
            kave_dot_control_dot_v1_dot_rbac__pb2.DeleteBindingRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestPermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.control.v1.RBACService/TestPermission',
            kave_dot_control_dot_v1_dot_rbac__pb2.TestPermissionRequest.SerializeToString,
            kave_dot_control_dot_v1_dot_rbac__pb2.TestPermissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
