# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kave/control/v1/token.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kave/control/v1/token.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from kave.common.v1 import common_pb2 as kave_dot_common_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bkave/control/v1/token.proto\x12\x0fkave.control.v1\x1a\x1bkave/common/v1/common.proto\"\x88\x04\n\nAgentToken\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x02 \x01(\t\x12\x12\n\nproject_id\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x14\n\x0ctoken_prefix\x18\x06 \x01(\t\x12\x0c\n\x04hash\x18\x07 \x01(\t\x12\x12\n\nissued_for\x18\x08 \x01(\t\x12\x11\n\tissued_by\x18\t \x01(\t\x12\x12\n\nconnectors\x18\n \x03(\t\x12\x0f\n\x07methods\x18\x0b \x03(\t\x12/\n\nbudget_cap\x18\x0c \x01(\x0b\x32\x16.kave.common.v1.AmountH\x00\x88\x01\x01\x12\x0e\n\x06scopes\x18\r \x03(\t\x12\x15\n\rnot_before_ms\x18\x0e \x01(\x03\x12\x1a\n\rexpires_at_ms\x18\x0f \x01(\x03H\x01\x88\x01\x01\x12\x1c\n\x0flast_used_at_ms\x18\x10 \x01(\x03H\x02\x88\x01\x01\x12\x1a\n\rrevoked_at_ms\x18\x11 \x01(\x03H\x03\x88\x01\x01\x12\x12\n\nrevoked_by\x18\x12 \x01(\t\x12\x15\n\rrevoke_reason\x18\x13 \x01(\t\x12\x15\n\rcreated_at_ms\x18\x14 \x01(\x03\x42\r\n\x0b_budget_capB\x10\n\x0e_expires_at_msB\x12\n\x10_last_used_at_msB\x10\n\x0e_revoked_at_ms\"\x96\x01\n\x10\x41gentTokenUpdate\x12\x1a\n\rrevoked_at_ms\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x17\n\nrevoked_by\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x1a\n\rrevoke_reason\x18\x03 \x01(\tH\x02\x88\x01\x01\x42\x10\n\x0e_revoked_at_msB\r\n\x0b_revoked_byB\x10\n\x0e_revoke_reasonB;Z9github.com/kave-io/kave/proto/gen/kave/control/v1;controlb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kave.control.v1.token_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/kave-io/kave/proto/gen/kave/control/v1;control'
  _globals['_AGENTTOKEN']._serialized_start=78
  _globals['_AGENTTOKEN']._serialized_end=598
  _globals['_AGENTTOKENUPDATE']._serialized_start=601
  _globals['_AGENTTOKENUPDATE']._serialized_end=751
# @@protoc_insertion_point(module_scope)
