# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kave.audit.v1 import audit_pb2 as kave_dot_audit_dot_v1_dot_audit__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kave/audit/v1/audit_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuditServiceStub(object):
    """Service for audit operations (gRPC v1).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AppendAudit = channel.unary_unary(
                '/kave.audit.v1.AuditService/AppendAudit',
                request_serializer=kave_dot_audit_dot_v1_dot_audit__pb2.AppendAuditRequest.SerializeToString,
                response_deserializer=kave_dot_audit_dot_v1_dot_audit__pb2.AuditLog.FromString,
                _registered_method=True)
        self.QueryAudits = channel.unary_unary(
                '/kave.audit.v1.AuditService/QueryAudits',
                request_serializer=kave_dot_audit_dot_v1_dot_audit__pb2.QueryAuditsRequest.SerializeToString,
                response_deserializer=kave_dot_audit_dot_v1_dot_audit__pb2.QueryAuditsResponse.FromString,
                _registered_method=True)


class AuditServiceServicer(object):
    """Service for audit operations (gRPC v1).
    """

    def AppendAudit(self, request, context):
        """AppendAudit adds an audit log entry (control plane only; not exposed to end users).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryAudits(self, request, context):
        """QueryAudits retrieves audit logs matching a filter.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuditServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AppendAudit': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendAudit,
                    request_deserializer=kave_dot_audit_dot_v1_dot_audit__pb2.AppendAuditRequest.FromString,
                    response_serializer=kave_dot_audit_dot_v1_dot_audit__pb2.AuditLog.SerializeToString,
            ),
            'QueryAudits': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryAudits,
                    request_deserializer=kave_dot_audit_dot_v1_dot_audit__pb2.QueryAuditsRequest.FromString,
                    response_serializer=kave_dot_audit_dot_v1_dot_audit__pb2.QueryAuditsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kave.audit.v1.AuditService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kave.audit.v1.AuditService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuditService(object):
    """Service for audit operations (gRPC v1).
    """

    @staticmethod
    def AppendAudit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.audit.v1.AuditService/AppendAudit',
            kave_dot_audit_dot_v1_dot_audit__pb2.AppendAuditRequest.SerializeToString,
            kave_dot_audit_dot_v1_dot_audit__pb2.AuditLog.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryAudits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.audit.v1.AuditService/QueryAudits',
            kave_dot_audit_dot_v1_dot_audit__pb2.QueryAuditsRequest.SerializeToString,
            kave_dot_audit_dot_v1_dot_audit__pb2.QueryAuditsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
