# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kave.runtime.v1 import fx_pb2 as kave_dot_runtime_dot_v1_dot_fx__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kave/runtime/v1/fx_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FXServiceStub(object):
    """FXService provides currency conversion and rate management.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListCurrencies = channel.unary_unary(
                '/kave.runtime.v1.FXService/ListCurrencies',
                request_serializer=kave_dot_runtime_dot_v1_dot_fx__pb2.ListCurrenciesRequest.SerializeToString,
                response_deserializer=kave_dot_runtime_dot_v1_dot_fx__pb2.ListCurrenciesResponse.FromString,
                _registered_method=True)
        self.ListRates = channel.unary_unary(
                '/kave.runtime.v1.FXService/ListRates',
                request_serializer=kave_dot_runtime_dot_v1_dot_fx__pb2.ListRatesRequest.SerializeToString,
                response_deserializer=kave_dot_runtime_dot_v1_dot_fx__pb2.ListRatesResponse.FromString,
                _registered_method=True)
        self.Convert = channel.unary_unary(
                '/kave.runtime.v1.FXService/Convert',
                request_serializer=kave_dot_runtime_dot_v1_dot_fx__pb2.ConvertRequest.SerializeToString,
                response_deserializer=kave_dot_runtime_dot_v1_dot_fx__pb2.ConvertResponse.FromString,
                _registered_method=True)
        self.Refresh = channel.unary_unary(
                '/kave.runtime.v1.FXService/Refresh',
                request_serializer=kave_dot_runtime_dot_v1_dot_fx__pb2.RefreshRequest.SerializeToString,
                response_deserializer=kave_dot_runtime_dot_v1_dot_fx__pb2.RefreshResponse.FromString,
                _registered_method=True)


class FXServiceServicer(object):
    """FXService provides currency conversion and rate management.
    """

    def ListCurrencies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Convert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Refresh(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FXServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListCurrencies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCurrencies,
                    request_deserializer=kave_dot_runtime_dot_v1_dot_fx__pb2.ListCurrenciesRequest.FromString,
                    response_serializer=kave_dot_runtime_dot_v1_dot_fx__pb2.ListCurrenciesResponse.SerializeToString,
            ),
            'ListRates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRates,
                    request_deserializer=kave_dot_runtime_dot_v1_dot_fx__pb2.ListRatesRequest.FromString,
                    response_serializer=kave_dot_runtime_dot_v1_dot_fx__pb2.ListRatesResponse.SerializeToString,
            ),
            'Convert': grpc.unary_unary_rpc_method_handler(
                    servicer.Convert,
                    request_deserializer=kave_dot_runtime_dot_v1_dot_fx__pb2.ConvertRequest.FromString,
                    response_serializer=kave_dot_runtime_dot_v1_dot_fx__pb2.ConvertResponse.SerializeToString,
            ),
            'Refresh': grpc.unary_unary_rpc_method_handler(
                    servicer.Refresh,
                    request_deserializer=kave_dot_runtime_dot_v1_dot_fx__pb2.RefreshRequest.FromString,
                    response_serializer=kave_dot_runtime_dot_v1_dot_fx__pb2.RefreshResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kave.runtime.v1.FXService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kave.runtime.v1.FXService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FXService(object):
    """FXService provides currency conversion and rate management.
    """

    @staticmethod
    def ListCurrencies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.runtime.v1.FXService/ListCurrencies',
            kave_dot_runtime_dot_v1_dot_fx__pb2.ListCurrenciesRequest.SerializeToString,
            kave_dot_runtime_dot_v1_dot_fx__pb2.ListCurrenciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.runtime.v1.FXService/ListRates',
            kave_dot_runtime_dot_v1_dot_fx__pb2.ListRatesRequest.SerializeToString,
            kave_dot_runtime_dot_v1_dot_fx__pb2.ListRatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Convert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.runtime.v1.FXService/Convert',
            kave_dot_runtime_dot_v1_dot_fx__pb2.ConvertRequest.SerializeToString,
            kave_dot_runtime_dot_v1_dot_fx__pb2.ConvertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Refresh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.runtime.v1.FXService/Refresh',
            kave_dot_runtime_dot_v1_dot_fx__pb2.RefreshRequest.SerializeToString,
            kave_dot_runtime_dot_v1_dot_fx__pb2.RefreshResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
