# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kave.runtime.v1 import action_pb2 as kave_dot_runtime_dot_v1_dot_action__pb2
from kave.runtime.v1 import cost_pb2 as kave_dot_runtime_dot_v1_dot_cost__pb2
from kave.runtime.v1 import run_pb2 as kave_dot_runtime_dot_v1_dot_run__pb2
from kave.runtime.v1 import runtime_pb2 as kave_dot_runtime_dot_v1_dot_runtime__pb2
from kave.runtime.v1 import span_pb2 as kave_dot_runtime_dot_v1_dot_span__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kave/runtime/v1/runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuntimeServiceStub(object):
    """RuntimeAPI exposes run, action, span, and cost operations.
    v1: gRPC only. HTTP transcoding deferred to v1.1+.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRun = channel.unary_unary(
                '/kave.runtime.v1.RuntimeService/CreateRun',
                request_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.CreateRunRequest.SerializeToString,
                response_deserializer=kave_dot_runtime_dot_v1_dot_run__pb2.RunRecord.FromString,
                _registered_method=True)
        self.GetRun = channel.unary_unary(
                '/kave.runtime.v1.RuntimeService/GetRun',
                request_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.GetRunRequest.SerializeToString,
                response_deserializer=kave_dot_runtime_dot_v1_dot_run__pb2.RunRecord.FromString,
                _registered_method=True)
        self.ListRuns = channel.unary_unary(
                '/kave.runtime.v1.RuntimeService/ListRuns',
                request_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.ListRunsRequest.SerializeToString,
                response_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.ListRunsResponse.FromString,
                _registered_method=True)
        self.UpdateRun = channel.unary_unary(
                '/kave.runtime.v1.RuntimeService/UpdateRun',
                request_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.UpdateRunRequest.SerializeToString,
                response_deserializer=kave_dot_runtime_dot_v1_dot_run__pb2.RunRecord.FromString,
                _registered_method=True)
        self.CancelRun = channel.unary_unary(
                '/kave.runtime.v1.RuntimeService/CancelRun',
                request_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.CancelRunRequest.SerializeToString,
                response_deserializer=kave_dot_runtime_dot_v1_dot_run__pb2.RunRecord.FromString,
                _registered_method=True)
        self.WatchRuns = channel.unary_stream(
                '/kave.runtime.v1.RuntimeService/WatchRuns',
                request_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.WatchRunsRequest.SerializeToString,
                response_deserializer=kave_dot_runtime_dot_v1_dot_run__pb2.RunRecord.FromString,
                _registered_method=True)
        self.CreateAction = channel.unary_unary(
                '/kave.runtime.v1.RuntimeService/CreateAction',
                request_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.CreateActionRequest.SerializeToString,
                response_deserializer=kave_dot_runtime_dot_v1_dot_action__pb2.ActionRecord.FromString,
                _registered_method=True)
        self.GetAction = channel.unary_unary(
                '/kave.runtime.v1.RuntimeService/GetAction',
                request_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.GetActionRequest.SerializeToString,
                response_deserializer=kave_dot_runtime_dot_v1_dot_action__pb2.ActionRecord.FromString,
                _registered_method=True)
        self.ListActions = channel.unary_unary(
                '/kave.runtime.v1.RuntimeService/ListActions',
                request_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.ListActionsRequest.SerializeToString,
                response_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.ListActionsResponse.FromString,
                _registered_method=True)
        self.OpenSpan = channel.unary_unary(
                '/kave.runtime.v1.RuntimeService/OpenSpan',
                request_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.OpenSpanRequest.SerializeToString,
                response_deserializer=kave_dot_runtime_dot_v1_dot_span__pb2.SpanRow.FromString,
                _registered_method=True)
        self.CloseSpan = channel.unary_unary(
                '/kave.runtime.v1.RuntimeService/CloseSpan',
                request_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.CloseSpanRequest.SerializeToString,
                response_deserializer=kave_dot_runtime_dot_v1_dot_span__pb2.SpanRow.FromString,
                _registered_method=True)
        self.GetSpan = channel.unary_unary(
                '/kave.runtime.v1.RuntimeService/GetSpan',
                request_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.GetSpanRequest.SerializeToString,
                response_deserializer=kave_dot_runtime_dot_v1_dot_span__pb2.SpanRow.FromString,
                _registered_method=True)
        self.QuerySpans = channel.unary_unary(
                '/kave.runtime.v1.RuntimeService/QuerySpans',
                request_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.QuerySpansRequest.SerializeToString,
                response_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.QuerySpansResponse.FromString,
                _registered_method=True)
        self.WatchEvents = channel.unary_stream(
                '/kave.runtime.v1.RuntimeService/WatchEvents',
                request_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.WatchEventsRequest.SerializeToString,
                response_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.RuntimeEvent.FromString,
                _registered_method=True)
        self.WatchLogs = channel.unary_stream(
                '/kave.runtime.v1.RuntimeService/WatchLogs',
                request_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.WatchLogsRequest.SerializeToString,
                response_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.LogLine.FromString,
                _registered_method=True)
        self.TailTraces = channel.unary_stream(
                '/kave.runtime.v1.RuntimeService/TailTraces',
                request_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.TailTracesRequest.SerializeToString,
                response_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.TraceEvent.FromString,
                _registered_method=True)
        self.StreamSpans = channel.unary_stream(
                '/kave.runtime.v1.RuntimeService/StreamSpans',
                request_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.StreamSpansRequest.SerializeToString,
                response_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.SpanEvent.FromString,
                _registered_method=True)
        self.ExportTrace = channel.unary_unary(
                '/kave.runtime.v1.RuntimeService/ExportTrace',
                request_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.ExportTraceRequest.SerializeToString,
                response_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.ExportTraceResponse.FromString,
                _registered_method=True)
        self.IngestTraces = channel.unary_unary(
                '/kave.runtime.v1.RuntimeService/IngestTraces',
                request_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.IngestTracesRequest.SerializeToString,
                response_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.IngestTracesResponse.FromString,
                _registered_method=True)
        self.GetPriceBook = channel.unary_unary(
                '/kave.runtime.v1.RuntimeService/GetPriceBook',
                request_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.GetPriceBookRequest.SerializeToString,
                response_deserializer=kave_dot_runtime_dot_v1_dot_cost__pb2.PriceBook.FromString,
                _registered_method=True)
        self.GetSpendReport = channel.unary_unary(
                '/kave.runtime.v1.RuntimeService/GetSpendReport',
                request_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.GetSpendReportRequest.SerializeToString,
                response_deserializer=kave_dot_runtime_dot_v1_dot_cost__pb2.SpendReport.FromString,
                _registered_method=True)
        self.GetDashboardOverview = channel.unary_unary(
                '/kave.runtime.v1.RuntimeService/GetDashboardOverview',
                request_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.GetDashboardOverviewRequest.SerializeToString,
                response_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.DashboardOverview.FromString,
                _registered_method=True)
        self.GetTraceGraph = channel.unary_unary(
                '/kave.runtime.v1.RuntimeService/GetTraceGraph',
                request_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.GetTraceGraphRequest.SerializeToString,
                response_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.TraceGraph.FromString,
                _registered_method=True)


class RuntimeServiceServicer(object):
    """RuntimeAPI exposes run, action, span, and cost operations.
    v1: gRPC only. HTTP transcoding deferred to v1.1+.
    """

    def CreateRun(self, request, context):
        """Run operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAction(self, request, context):
        """Action operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListActions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenSpan(self, request, context):
        """Span operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSpan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSpan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuerySpans(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchEvents(self, request, context):
        """Streaming operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TailTraces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSpans(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportTrace(self, request, context):
        """Trace operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestTraces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPriceBook(self, request, context):
        """Cost operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSpendReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDashboardOverview(self, request, context):
        """Aggregate read models
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTraceGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRun,
                    request_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.CreateRunRequest.FromString,
                    response_serializer=kave_dot_runtime_dot_v1_dot_run__pb2.RunRecord.SerializeToString,
            ),
            'GetRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRun,
                    request_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.GetRunRequest.FromString,
                    response_serializer=kave_dot_runtime_dot_v1_dot_run__pb2.RunRecord.SerializeToString,
            ),
            'ListRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRuns,
                    request_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.ListRunsRequest.FromString,
                    response_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.ListRunsResponse.SerializeToString,
            ),
            'UpdateRun': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRun,
                    request_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.UpdateRunRequest.FromString,
                    response_serializer=kave_dot_runtime_dot_v1_dot_run__pb2.RunRecord.SerializeToString,
            ),
            'CancelRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRun,
                    request_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.CancelRunRequest.FromString,
                    response_serializer=kave_dot_runtime_dot_v1_dot_run__pb2.RunRecord.SerializeToString,
            ),
            'WatchRuns': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchRuns,
                    request_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.WatchRunsRequest.FromString,
                    response_serializer=kave_dot_runtime_dot_v1_dot_run__pb2.RunRecord.SerializeToString,
            ),
            'CreateAction': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAction,
                    request_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.CreateActionRequest.FromString,
                    response_serializer=kave_dot_runtime_dot_v1_dot_action__pb2.ActionRecord.SerializeToString,
            ),
            'GetAction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAction,
                    request_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.GetActionRequest.FromString,
                    response_serializer=kave_dot_runtime_dot_v1_dot_action__pb2.ActionRecord.SerializeToString,
            ),
            'ListActions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListActions,
                    request_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.ListActionsRequest.FromString,
                    response_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.ListActionsResponse.SerializeToString,
            ),
            'OpenSpan': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenSpan,
                    request_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.OpenSpanRequest.FromString,
                    response_serializer=kave_dot_runtime_dot_v1_dot_span__pb2.SpanRow.SerializeToString,
            ),
            'CloseSpan': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSpan,
                    request_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.CloseSpanRequest.FromString,
                    response_serializer=kave_dot_runtime_dot_v1_dot_span__pb2.SpanRow.SerializeToString,
            ),
            'GetSpan': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSpan,
                    request_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.GetSpanRequest.FromString,
                    response_serializer=kave_dot_runtime_dot_v1_dot_span__pb2.SpanRow.SerializeToString,
            ),
            'QuerySpans': grpc.unary_unary_rpc_method_handler(
                    servicer.QuerySpans,
                    request_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.QuerySpansRequest.FromString,
                    response_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.QuerySpansResponse.SerializeToString,
            ),
            'WatchEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchEvents,
                    request_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.WatchEventsRequest.FromString,
                    response_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.RuntimeEvent.SerializeToString,
            ),
            'WatchLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchLogs,
                    request_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.WatchLogsRequest.FromString,
                    response_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.LogLine.SerializeToString,
            ),
            'TailTraces': grpc.unary_stream_rpc_method_handler(
                    servicer.TailTraces,
                    request_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.TailTracesRequest.FromString,
                    response_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.TraceEvent.SerializeToString,
            ),
            'StreamSpans': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSpans,
                    request_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.StreamSpansRequest.FromString,
                    response_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.SpanEvent.SerializeToString,
            ),
            'ExportTrace': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportTrace,
                    request_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.ExportTraceRequest.FromString,
                    response_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.ExportTraceResponse.SerializeToString,
            ),
            'IngestTraces': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestTraces,
                    request_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.IngestTracesRequest.FromString,
                    response_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.IngestTracesResponse.SerializeToString,
            ),
            'GetPriceBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPriceBook,
                    request_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.GetPriceBookRequest.FromString,
                    response_serializer=kave_dot_runtime_dot_v1_dot_cost__pb2.PriceBook.SerializeToString,
            ),
            'GetSpendReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSpendReport,
                    request_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.GetSpendReportRequest.FromString,
                    response_serializer=kave_dot_runtime_dot_v1_dot_cost__pb2.SpendReport.SerializeToString,
            ),
            'GetDashboardOverview': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDashboardOverview,
                    request_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.GetDashboardOverviewRequest.FromString,
                    response_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.DashboardOverview.SerializeToString,
            ),
            'GetTraceGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTraceGraph,
                    request_deserializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.GetTraceGraphRequest.FromString,
                    response_serializer=kave_dot_runtime_dot_v1_dot_runtime__pb2.TraceGraph.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kave.runtime.v1.RuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kave.runtime.v1.RuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuntimeService(object):
    """RuntimeAPI exposes run, action, span, and cost operations.
    v1: gRPC only. HTTP transcoding deferred to v1.1+.
    """

    @staticmethod
    def CreateRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.runtime.v1.RuntimeService/CreateRun',
            kave_dot_runtime_dot_v1_dot_runtime__pb2.CreateRunRequest.SerializeToString,
            kave_dot_runtime_dot_v1_dot_run__pb2.RunRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.runtime.v1.RuntimeService/GetRun',
            kave_dot_runtime_dot_v1_dot_runtime__pb2.GetRunRequest.SerializeToString,
            kave_dot_runtime_dot_v1_dot_run__pb2.RunRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.runtime.v1.RuntimeService/ListRuns',
            kave_dot_runtime_dot_v1_dot_runtime__pb2.ListRunsRequest.SerializeToString,
            kave_dot_runtime_dot_v1_dot_runtime__pb2.ListRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.runtime.v1.RuntimeService/UpdateRun',
            kave_dot_runtime_dot_v1_dot_runtime__pb2.UpdateRunRequest.SerializeToString,
            kave_dot_runtime_dot_v1_dot_run__pb2.RunRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.runtime.v1.RuntimeService/CancelRun',
            kave_dot_runtime_dot_v1_dot_runtime__pb2.CancelRunRequest.SerializeToString,
            kave_dot_runtime_dot_v1_dot_run__pb2.RunRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kave.runtime.v1.RuntimeService/WatchRuns',
            kave_dot_runtime_dot_v1_dot_runtime__pb2.WatchRunsRequest.SerializeToString,
            kave_dot_runtime_dot_v1_dot_run__pb2.RunRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.runtime.v1.RuntimeService/CreateAction',
            kave_dot_runtime_dot_v1_dot_runtime__pb2.CreateActionRequest.SerializeToString,
            kave_dot_runtime_dot_v1_dot_action__pb2.ActionRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.runtime.v1.RuntimeService/GetAction',
            kave_dot_runtime_dot_v1_dot_runtime__pb2.GetActionRequest.SerializeToString,
            kave_dot_runtime_dot_v1_dot_action__pb2.ActionRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListActions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.runtime.v1.RuntimeService/ListActions',
            kave_dot_runtime_dot_v1_dot_runtime__pb2.ListActionsRequest.SerializeToString,
            kave_dot_runtime_dot_v1_dot_runtime__pb2.ListActionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenSpan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.runtime.v1.RuntimeService/OpenSpan',
            kave_dot_runtime_dot_v1_dot_runtime__pb2.OpenSpanRequest.SerializeToString,
            kave_dot_runtime_dot_v1_dot_span__pb2.SpanRow.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSpan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.runtime.v1.RuntimeService/CloseSpan',
            kave_dot_runtime_dot_v1_dot_runtime__pb2.CloseSpanRequest.SerializeToString,
            kave_dot_runtime_dot_v1_dot_span__pb2.SpanRow.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSpan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.runtime.v1.RuntimeService/GetSpan',
            kave_dot_runtime_dot_v1_dot_runtime__pb2.GetSpanRequest.SerializeToString,
            kave_dot_runtime_dot_v1_dot_span__pb2.SpanRow.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuerySpans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.runtime.v1.RuntimeService/QuerySpans',
            kave_dot_runtime_dot_v1_dot_runtime__pb2.QuerySpansRequest.SerializeToString,
            kave_dot_runtime_dot_v1_dot_runtime__pb2.QuerySpansResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kave.runtime.v1.RuntimeService/WatchEvents',
            kave_dot_runtime_dot_v1_dot_runtime__pb2.WatchEventsRequest.SerializeToString,
            kave_dot_runtime_dot_v1_dot_runtime__pb2.RuntimeEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kave.runtime.v1.RuntimeService/WatchLogs',
            kave_dot_runtime_dot_v1_dot_runtime__pb2.WatchLogsRequest.SerializeToString,
            kave_dot_runtime_dot_v1_dot_runtime__pb2.LogLine.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TailTraces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kave.runtime.v1.RuntimeService/TailTraces',
            kave_dot_runtime_dot_v1_dot_runtime__pb2.TailTracesRequest.SerializeToString,
            kave_dot_runtime_dot_v1_dot_runtime__pb2.TraceEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSpans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kave.runtime.v1.RuntimeService/StreamSpans',
            kave_dot_runtime_dot_v1_dot_runtime__pb2.StreamSpansRequest.SerializeToString,
            kave_dot_runtime_dot_v1_dot_runtime__pb2.SpanEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportTrace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.runtime.v1.RuntimeService/ExportTrace',
            kave_dot_runtime_dot_v1_dot_runtime__pb2.ExportTraceRequest.SerializeToString,
            kave_dot_runtime_dot_v1_dot_runtime__pb2.ExportTraceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestTraces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.runtime.v1.RuntimeService/IngestTraces',
            kave_dot_runtime_dot_v1_dot_runtime__pb2.IngestTracesRequest.SerializeToString,
            kave_dot_runtime_dot_v1_dot_runtime__pb2.IngestTracesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPriceBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.runtime.v1.RuntimeService/GetPriceBook',
            kave_dot_runtime_dot_v1_dot_runtime__pb2.GetPriceBookRequest.SerializeToString,
            kave_dot_runtime_dot_v1_dot_cost__pb2.PriceBook.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSpendReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.runtime.v1.RuntimeService/GetSpendReport',
            kave_dot_runtime_dot_v1_dot_runtime__pb2.GetSpendReportRequest.SerializeToString,
            kave_dot_runtime_dot_v1_dot_cost__pb2.SpendReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDashboardOverview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.runtime.v1.RuntimeService/GetDashboardOverview',
            kave_dot_runtime_dot_v1_dot_runtime__pb2.GetDashboardOverviewRequest.SerializeToString,
            kave_dot_runtime_dot_v1_dot_runtime__pb2.DashboardOverview.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTraceGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kave.runtime.v1.RuntimeService/GetTraceGraph',
            kave_dot_runtime_dot_v1_dot_runtime__pb2.GetTraceGraphRequest.SerializeToString,
            kave_dot_runtime_dot_v1_dot_runtime__pb2.TraceGraph.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
